markdown: rdiscount
pygments: true
permalink: /posts/:year/:month/:day/:title
rdiscount:
  extensions: [smart]
exclude: [ Gemfile, Gemfile.lock, gems, _assets, bower_components ]
title : kindohm
production_url : http://kindohm.com
description: "Mike Hodnick's personal web site and blog"
disqus_shortname: kindohm
analytics: UA-3329895-3
gauges: 
author :
  name : Mike Hodnick
  github : kindohm
  twitter : kindohm
  email: mike.hodnick@gmail.com
  linkedin: michaelhodnick
