permalink: /posts/:year/:month/:day/:title 

exclude: [".rvmrc", ".rbenv-version", "readme.md", "Rakefile", "changelog.md", "run.cmd", "Gemfile", "Gemfile.lock"]
pygments: false

title : Kindohm
tagline: Kindohm
author :
  name : Mike Hodnick
  email : kindohm@gmail.com
  github : kindohm
  twitter : kindohm
  feedburner : Kindohm

production_url : http://kindohm.com
